### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by reqTibi** [IBM/ELM-Python-Client#34]
Hello,

I'm starting now with the library and I do succeed to login to the system. The Jazz is configured to have automatic (Windows) login via Active Directory. I specified the environment variables QUERY_JAZZURL, QUERY_USER and QUERY_PASSWORD with the correct values but the query:

`reqif_io.exe -F "Initial Stream" -C "Overall requirements" "Rocket project" list` 

throws:
`requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://<<jazzurl>>/rm/process/project-areas`

What do I wrong or what I need to specify to get connected.

The oslcquery command works with the same settings.

**Comment by barny** [comment]
Hi - turns out there's a typo and the environment variable for the password is currently OUERY_PASSWORD i.e. first letter is capital O not Q like it should be. Let me know if that works?

**Comment by reqTibi** [comment]
Hello, yes it look good now. I'm able to use the script.

**Comment by barny** [comment]
Thanks for confirming, I'll update to fix it in a few days. FYI there is the same problem for represt.py

**Comment by barny** [comment]
Release 0.17.0 fixes the type with QUERY_PASSWORD
