### ISSUE TITLE
Different results whith same osclquery

### ISSUE THREAD

**Issue by sergiomarsen** [IBM/ELM-Python-Client#45]
Hello,
I am experiencing some issues when requesting same oslcquery to Doors NG.

The type of request i am using is like the following:

```shell
oslcquery -J https://my.server:port -U usr -P pwd -A rm,gc,jts:jts23 -p "Project Name" -C "Module_Name" -F "Local Stream Name" -q "oslc:instanceShape in ['Artifact type 1','Arctifact Type 2']" -O "data/projName/reqs.csv" -s "dcterms:identifier,oslc:instanceShape,rm:module" -W
``` 

Also tried without any query(-q) just to check if it was the problem:

```shell
oslcquery -J https://my.server:port -U usr -P pwd -A rm,gc,jts:jts23 -p "Project Name" -C "Module_Name" -F "Local Stream Name" -O "data/projName/reqs.csv" -s "dcterms:identifier,oslc:instanceShape,rm:module" -W
```

But the result is the same:

We get different results by executing the same request (with no changes applied in doors side).
For instance we execute it once and get the correct result (e.g. 7500 requirements), and 5 minutes later do it again and only get 7000 requirements.

I don't know if is there any limitations on how many results the oslcquery can return at once. But it seems strange that sometimes it works pretty fine but other times it misses some results. 

I would really appreciate if you have any suggestion on how could I proceed to avoid this behaviour. 

Thanks a lot in advance!

Regards,
Sergio

**Comment by sergiomarsen** [comment]
Well, with the number of results I meant the ones once filtered. But the amount of all of them is around 25000 entries (without applying the -q query)
It also does not displays any errors, just the result sometimes misses some entries

**Comment by barny** [comment]
I've got a project with 30k artifacts which I can query, using iFix023. There may have been defects fixed around APIs since 013 - best thing would be to update to SR1 and iFix 023, and try again.

**Comment by barny** [comment]
hmm, found the number of results does seem to vary - if you set `--pagesize 0` then that seems to give stable results alebit with very large pages but works for me with 130k artifacts in the component. Must be something to do with combining all the pages of results.

**Comment by sergiomarsen** [comment]
Hi barny, 
Thanks a lot, we still have to upgrade the iFix but with the pagesize workaround you commented it seems to be returning always the same number of results with the request I was experiencing that problem. That helps us a lot :)

So just one more  thing to comment regarding this.
I guess by establishing the pagesize to 0 we are doing like a search for all entries in just one page with "unlimited" entries size.
I have tried also establishing the pagesize to a number greater than the expected results and seems to works alright too. (if the page size is set lower than total results, again the results does vary, so it really seems to be solving this)

That's why I was wondering if you know whether there is kind of a "easy-reachable" limit in this page size and if so, if there is a way to do another request with an "start at" attribute or something like that to begin since the last result of the previous request. I mean, for a later post-processing with the data extracted from the 2/more requests

This is just something I was thinking in case it fails with more data amount, but for now it is working fine for us with just one page as commented.

Thanks a lot for the help!

**Comment by barny** [comment]
Setting page size to 0 is a workaround - I'll try to fix the issue.
