### ISSUE TITLE
New User: How to use OSLCQuery correctly

### ISSUE THREAD

**Issue by davesedar** [IBM/ELM-Python-Client#56]
I am trying to follow the github article: https://github.com/IBM/ELM-Python-Client/blob/master/elmclient/examples/OSLCQUERY.md

to use OSLCQuery on our SaaS Test Manager.

My query (run from a command prompt) :
oslcquery -J "[https://telent-dng.clm.ibmcloud.com/"](https://telent-dng.clm.ibmcloud.com/%22) -A qm -p "TPCMS inc RemoteSecure" -P "xxx*" -U "xxx" -s dcterms:title -O qmresults.csv

returns the unhelpful response:
File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\daves\anaconda3\Scripts\oslcquery.exe__main__.py", line 7, in <module>
  File "C:\Users\daves\anaconda3\Lib\site-packages\elmclient\examples\oslcquery.py", line 814, in main
    do_oslc_query(sys.argv[1:])
  File "C:\Users\daves\anaconda3\Lib\site-packages\elmclient\examples\oslcquery.py", line 359, in do_oslc_query
    c = p.find_local_component(args.component)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daves\anaconda3\Lib\site-packages\elmclient_qm.py", line 291, in find_local_component
    self.load_components_and_configurations()
  File "C:\Users\daves\anaconda3\Lib\site-packages\elmclient_qm.py", line 72, in load_components_and_configurations
    assert compuri is not None, "compuri is None"
           ^^^^^^^^^^^^^^^^^^^
AssertionError: compuri is None
Version 0.23.0
Warning - project 'TPCMS inc RemoteSecure' is opt-in but you didn't specify a component or a global configuration - using default component 'TPCMS inc RemoteSecure' - if this component name doesn't exist you'll get an error message

so far as I can tell our SaaS v7.0.2 Project is opt-in, but even adding '-C 8371'  produces no .csv file,
what am I doing wrong?
David Sedar

**Comment by barny** [comment]
Hi - First thing you should do is update to latest version 0.25.0 and see if that works better.

If the component isn't the default one then you shoudl specify the component like yes `-C 8371`

If the configuration isn't the default one then you must specify the configuration `-F myconfigname`

**Comment by davesedar** [comment]
Ian,
I have updated to 0.25.0, rebooted for good measure and  added -C 8371, but
still getting the same lack of anything useful.

There is definitely no file qmresults created anywhere on my pc.

I am not sure where to look in ETM for the configuration name

Regards
DAS

**Comment by davesedar** [comment]
Ian,
I wish this was easier:
We are using V7.0.2 SR1 (iFix 025) on IBM SaaS,
I can certainly see the Project Name "TPCMS inc RemoteSecure" to the right
of the 'Home Menu' button on the black bar, but there is no vertical bar or
Component Name or Configuration Name (screenshot attached).
I've just updated anaconda to latest v2.5.2 and python is 3.11.5.

Python 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23)
[MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

Regards
DAS

**Comment by barny** [comment]
>  the Project Name "TPCMS inc RemoteSecure" to the right of the 'Home Menu' button on the black bar, but there is no vertical bar or Component Name or Configuration Name

Your screenshot seems not to have worked.

That sounds like you don't have configuration management enabled on the project.

So I can see exactly where the error is happening , wen you run your oslcquery command at the command prompt please show the command and the full text output as text (with appropriate things XXXed) not screenshot.

**Comment by davesedar** [comment]
Ian,
Yes, you are correct: We do not have Configuration Management enabled.
I have found the vertical bar and Component Name - I hadn't realized it
only appears on /rm, not on /qm.

However, the error remains, even after I specify the -F and -C arguments:
C:\Users\daves>oslcquery -J "https://telent-dng.clm.ibmcloud.com/" -A qm -p
"TPCMS inc RemoteSecure" -P "xxx" -U "xxx" -F "TPCMS inc RemoteSecure
Initial Stream" -s dcterms:title -O qmresults.csv -C 8371
Version 0.25.0
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\daves\anaconda3\Scripts\oslcquery.exe\__main__.py", line
7, in <module>
  File
"C:\Users\daves\anaconda3\Lib\site-packages\elmclient\examples\oslcquery.py",
line 814, in main
    do_oslc_query(sys.argv[1:])
  File
"C:\Users\daves\anaconda3\Lib\site-packages\elmclient\examples\oslcquery.py",
line 359, in do_oslc_query
    c = p.find_local_component(args.component)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daves\anaconda3\Lib\site-packages\elmclient\_qm.py", line
291, in find_local_component
    self.load_components_and_configurations()
  File "C:\Users\daves\anaconda3\Lib\site-packages\elmclient\_qm.py", line
72, in load_components_and_configurations
    assert compuri is not None, "compuri is None"
           ^^^^^^^^^^^^^^^^^^^
AssertionError: compuri is None

C:\Users\daves>

Where next?
Regards
DAS

**Comment by barny** [comment]
This is when remote debugging gets complicated. I can't understand how the code has got to where your run fails, I suspect it must be something to do with your data.

Run the command again with added `-L TRACE` - this will create a new log file below a subdirectory `logs` from wherever you ran the command.

In that file, search for a line like this with your project name instead of my project name optout:

<jp06:project-area jp06:name="**optout**">

The complete tag which describes the project will look like this XML below, please share your tag for your project.

    <jp06:project-area jp06:name="**optout**">
        <jp06:summary/>
        <jp06:description/>
        <jp06:url>https://jazz.ibm.com:9443/qm/process/project-areas/_7A3tILFbEe6UzdHPm7EG5w</jp06:url>
        <jp06:roles-url>https://jazz.ibm.com:9443/qm/process/project-areas/_7A3tILFbEe6UzdHPm7EG5w/roles</jp06:roles-url>
        <jp06:links-url>https://jazz.ibm.com:9443/qm/process/project-areas/_7A3tILFbEe6UzdHPm7EG5w/links</jp06:links-url>
        <jp06:members-url>https://jazz.ibm.com:9443/qm/process/project-areas/_7A3tILFbEe6UzdHPm7EG5w/members</jp06:members-url>
        <jp:admins-url xmlns:jp="http://jazz.net/xmlns/prod/jazz/process/1.0/">https://jazz.ibm.com:9443/qm/process/project-areas/_7A3tILFbEe6UzdHPm7EG5w/admins</jp:admins-url>
        <jp06:team-areas-url>https://jazz.ibm.com:9443/qm/process/project-areas/_7A3tILFbEe6UzdHPm7EG5w/team-areas</jp06:team-areas-url>
        <jp06:project-admins-url>https://jazz.ibm.com:9443/qm/process/project-areas/_7A3tILFbEe6UzdHPm7EG5w/project-admins</jp06:project-admins-url>
        <jp06:read-access-list-url>https://jazz.ibm.com:9443/qm/process/project-areas/_7A3tILFbEe6UzdHPm7EG5w/read-access-list</jp06:read-access-list-url>
        <jp:timelines-url xmlns:jp="http://jazz.net/xmlns/prod/jazz/process/1.0/">https://jazz.ibm.com:9443/qm/process/project-areas/_7A3tILFbEe6UzdHPm7EG5w/timelines</jp:timelines-url>
        <jp06:access-public>false</jp06:access-public>
        <jp06:access-visible-to-access-list>false</jp06:access-visible-to-access-list>
        <jp06:access-visible-to-members>true</jp06:access-visible-to-members>
        <jp06:modified>Fri, 12 Jan 2024 15:05:55 GMT</jp06:modified>
        <jp06:archived>false</jp06:archived>
        <jp:history-url xmlns:jp="http://jazz.net/xmlns/prod/jazz/process/1.0/">https://jazz.ibm.com:9443/qm/process/project-areas/_7A3tILFbEe6UzdHPm7EG5w/history</jp:history-url>
        <jp:configuration-management-enabled xmlns:jp="http://jazz.net/xmlns/prod/jazz/process/1.0/">false</jp:configuration-management-enabled>
        <jp:configuration-management-mode xmlns:jp="http://jazz.net/xmlns/prod/jazz/process/1.0/">OPTOUT</jp:configuration-management-mode>
    </jp06:project-area>
</jp06:project-areas>

Please share the complete jp06:project-area tag for your project.

**Comment by davesedar** [comment]
Ian,
<jp06:project-area  as requested:
<jp06:project-area jp06:name="TPCMS inc RemoteSecure">
        <jp06:summary>SCADA Test Management Project</jp06:summary>
        <jp06:description/>
        <jp06:url>
https://telent-dng.clm.ibmcloud.com/qm/process/project-areas/_Ihj2YHCWEe2S4oZCjyXncw
</jp06:url>
        <jp06:roles-url>
https://telent-dng.clm.ibmcloud.com/qm/process/project-areas/_Ihj2YHCWEe2S4oZCjyXncw/roles
</jp06:roles-url>
        <jp06:links-url>
https://telent-dng.clm.ibmcloud.com/qm/process/project-areas/_Ihj2YHCWEe2S4oZCjyXncw/links
</jp06:links-url>
        <jp06:members-url>
https://telent-dng.clm.ibmcloud.com/qm/process/project-areas/_Ihj2YHCWEe2S4oZCjyXncw/members
</jp06:members-url>
        <jp:admins-url xmlns:jp="
http://jazz.net/xmlns/prod/jazz/process/1.0/">
https://telent-dng.clm.ibmcloud.com/qm/process/project-areas/_Ihj2YHCWEe2S4oZCjyXncw/admins
</jp:admins-url>
        <jp06:team-areas-url>
https://telent-dng.clm.ibmcloud.com/qm/process/project-areas/_Ihj2YHCWEe2S4oZCjyXncw/team-areas
</jp06:team-areas-url>
        <jp06:project-admins-url>
https://telent-dng.clm.ibmcloud.com/qm/process/project-areas/_Ihj2YHCWEe2S4oZCjyXncw/project-admins
</jp06:project-admins-url>
        <jp06:read-access-list-url>
https://telent-dng.clm.ibmcloud.com/qm/process/project-areas/_Ihj2YHCWEe2S4oZCjyXncw/read-access-list
</jp06:read-access-list-url>
        <jp:timelines-url xmlns:jp="
http://jazz.net/xmlns/prod/jazz/process/1.0/">
https://telent-dng.clm.ibmcloud.com/qm/process/project-areas/_Ihj2YHCWEe2S4oZCjyXncw/timelines
</jp:timelines-url>
        <jp06:access-public>false</jp06:access-public>

<jp06:access-visible-to-access-list>false</jp06:access-visible-to-access-list>

<jp06:access-visible-to-members>true</jp06:access-visible-to-members>
        <jp06:modified>Thu, 04 Jan 2024 15:37:44 GMT</jp06:modified>
        <jp06:archived>false</jp06:archived>
        <jp:history-url xmlns:jp="
http://jazz.net/xmlns/prod/jazz/process/1.0/">
https://telent-dng.clm.ibmcloud.com/qm/process/project-areas/_Ihj2YHCWEe2S4oZCjyXncw/history
</jp:history-url>
        <jp:configuration-management-enabled xmlns:jp="
http://jazz.net/xmlns/prod/jazz/process/1.0/
">true</jp:configuration-management-enabled>
        <jp:configuration-management-mode xmlns:jp="
http://jazz.net/xmlns/prod/jazz/process/1.0/
">SINGLE</jp:configuration-management-mode>
    </jp06:project-area>

I did also try running as an Admin user, but it made no difference.
Hope this helps
Regards
DAS

**Comment by davesedar** [comment]
Ian,
I can confirm that our projects have no need for Full Configuration
Management and would prefer to stay that way.
I am very happy to only being able to query the main stream.
So, I should be very grateful if you make the change to your OSLCQuery
package.
Regards
David Sedar

**Comment by barny** [comment]
OK version 0.26 is now on pypi - for ETM (QM) a project with Configuration Management set to "Enable baselines" will now be treated as optout i.e. no need to provide a component or configuration - so you can't query baselines.
