### ISSUE TITLE
dn_simple_modulestructure.py fails with an exception when provided a module name that also has other similarly named requirement artifacts

### ISSUE THREAD

**Issue by mehtasamit** [IBM/ELM-Python-Client#61]
When running the python program [dn_simple_modulestructure.py](https://github.com/IBM/ELM-Python-Client/blob/master/elmclient/examples/dn_simple_modulestructure.py), the following exception error is raised: 
`More than one module with that name in project <project name> component <component name> configuraition <configuration name>`

It seems that the filter parameters passed using whereterms on line 175 are only partially used - just the OSLC "title" property is matched, and second filter term, the Artifact Format type of Module, seems to be ignored.

When I made the Module name (OSLC title property) unique from all the other requirement artifact names in the component, I was able to successfully execute the program.

I was also unable to fix the whereterms even though I used the fully qualified (using the full namespace URI for jazz_rm) uri for Module Artifact format name (as returned by the query). i.e. the following change didn't work either:
```
   whereterms = [
        ["dcterms:title", "=", f'"{mod}"'],
        [
            "rdm_types:ArtifactFormat",
            "=",
            f'"{rdfxml.RDF_DEFAULT_PREFIX["jazz_rm"]}Module"',
        ],
    ]

```

**Comment by barny** [comment]
Sorry taken me a while to get to looking at this.

The solution seems to be to change

`        whereterms=[['dcterms:title','=',f'"{mod}"'], ['rdm_types:ArtifactFormat','=','jazz_rm:Module']],`

to:

`        whereterms=[['dcterms:title','=',f'"{mod}"'], ['rdf:type','=','<http://jazz.net/ns/rm#Module>']],`

i.e. expand the prefix on the rhs of the second erm so it's an explicit URL. TBH I don't know why this is needed.

**Comment by mehtasamit** [comment]
Thanks.  I was missing the angle brackets - forgot about the OSCL Query syntax for URL. Good to know that oslcquery handles this automatically.
