### ISSUE TITLE
examples for oslcquery with IBM cloud (trial)?

### ISSUE THREAD

**Issue by ukuko** [IBM/ELM-Python-Client#63]
is there a possibility to provide a working example to use oslcquery with IBM cloud? in our case, it is trial, as we are testing a new version.

we set:
set QUERY_JAZZURL=https://jazz.net
set QUERY_USER=xxx
set QUERY_PASSWORD=xxx
set QUERY_JTS=sandbox01-qm

and then we run:
oslcquery **-A qm:sandbox01-qm,gc:sandbox01-gc** -G "abc (Global Configuration) Initial Development" -p "abc (Quality Management)" -E "abc (Global Configuration)" -O testcases_jazz.csv -s *

similar composition and parameters work  with our current server.

We are getting errors like:

```
Version 0.26.2
Exception on retrying request. URL: https://jazz.net/sandbox01-gc/process/project-areas, 401, 
Error 401: CRJZS0360I The remote authorization server is requesting user authorization to access the remote service provider&#39;s resources.
...

  File "C:\Program Files\Python312\Lib\site-packages\elmclient\httpops.py", line 622, in _execute_one_request_with_login
    response.raise_for_status()
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://jazz.net/sandbox01-gc/process/project-areas

```

We were also checking for a solution here: https://github.com/IBM/ELM-Python-Client/issues/43 , without sucess

thanks for any help!

**Comment by barny** [comment]
Hi - haven't tried against a sandbox before. The sandboxes have some extra security that prevents discovering the projects, so I'm sorry it is not possible to use oslcquery against your sandbox.

**Comment by ukuko** [comment]
all right, thanks anyway
